AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Runtime: python3.9
    Architectures:
      - x86_64

Resources:
  GymMatrixBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: gym-matrix
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt GymMatrixBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  GenerateMatrixFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/generate/
      Handler: app.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /generate
            Method: post
            RestApiId: !Ref ServerlessRestApi
        Options:
          Type: Api
          Properties:
            Path: /generate
            Method: options
            RestApiId: !Ref ServerlessRestApi
      Environment:
        Variables:
          BUCKET_NAME: !Ref GymMatrixBucket

  SolveMatrixFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/solve/
      Handler: app.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /solve
            Method: post
            RestApiId: !Ref ServerlessRestApi
        Options:
          Type: Api
          Properties:
            Path: /solve
            Method: options
            RestApiId: !Ref ServerlessRestApi
      Environment:
        Variables:
          BUCKET_NAME: !Ref GymMatrixBucket

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  MatrixGymCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: matrixgym-deploy
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: GITHUB
        Location: https://github.com/robertomdiniz/MatrixGym
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
      Source:
        Type: GITHUB
        Location: https://github.com/robertomdiniz/MatrixGym
        BuildSpec: buildspec.yml
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: ^refs/heads/main$

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub '${GymMatrixBucket}/*'
              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/*'

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  
  WebsiteUrl:
    Description: "S3 Website URL"
    Value: !GetAtt GymMatrixBucket.WebsiteURL

  CloudFrontUrl:
    Description: "CloudFront HTTPS URL"
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
